### ISSUE TITLE
Mahima Week 4 Review Ticket

### ISSUE THREAD

**Issue by shrutiapcsp** [yolandayangg/n224p4-beans#30]
1. Attendance, tutorial makeup if missing time, activity, individual questions, work habits, tutorial if behind.
2. Individual Runtime review on About Page progress/quality.
3. Individual Analytics (Issues with Tangibles, Commits)
4. CB progress, focus is on CB-exam MCQ test and improvement plan
5. Expertise in one or more of the following...  Procedures, Blueprint, Jekyll, Deployment Certbot, Databases, Wikie Policies, Branching strategies,	SCSS, Async with Fetch

**Comment by mahimak19** [comment]
5/5 
Had attendance, went to teacher to figure out deployment during 5th period, asked questions, worked on pages during class. About Page is complete, all elements are working. Commits are linked on Readme, and tangibles are present. Did corrections for CB MCQ test, quizzes are done. For technicals, I did a procedure that involved alphabetically ordering an array of strings.

**Comment by mahimak19** [comment]
I think I deserve a 4.75/5 because I had attendance, went to teacher to figure out deployment during 5th period, asked questions, worked on pages during class. About Page is complete, all elements are working. Commits are linked on Readme, and tangibles are present. Did corrections for CB MCQ test, quizzes are done. For technicals, I did a procedure that involved alphabetically ordering an array of strings. I could have done more advanced technicals that related to the PBL theme to learn more about raw coding and procedures.

During Review we discussed that I needed to have more raw coding technicals instead of a bunch of procedural abstraction. I am also behind on deployment, which I will get fixed soon. We also talked about putting a Blueprint, where each person makes their own python file and puts all their app routes there and simply calls them in main.
