### ISSUE TITLE
Natalie Week 4 Review Ticket

### ISSUE THREAD

**Issue by shrutiapcsp** [yolandayangg/n224p4-beans#33]
1. Attendance, tutorial makeup if missing time, activity, individual questions, work habits, tutorial if behind.
2. Individual Runtime review on About Page progress/quality.
3. Individual Analytics (Issues with Tangibles, Commits)
4. CB progress, focus is on CB-exam MCQ test and improvement plan
5. Expertise in one or more of the following...  Procedures, Blueprint, Jekyll, Deployment Certbot, Databases, Wikie Policies, Branching strategies,	SCSS, Async with Fetch

**Comment by nataliecohen** [comment]
4.5/5 - need more understanding in Fetch and Database 
1. Attendance, tutorial makeup if missing time, activity, individual questions, work habits, tutorial if behind.
2. Individual Runtime review on About Page progress/quality.
3. Individual Analytics (Issues with Tangibles, Commits)
4. CB progress, focus is on CB-exam MCQ test and improvement plan
5. Expertise in one or more of the following... Procedures, Blueprint, Jekyll, Deployment Certbot, Databases, Wikie Policies, Branching strategies, SCSS, Async with Fetch

**Comment by nataliecohen** [comment]
I think I deserve a 4.5/5 because I was always an active participant in class, working with my group, talking with my peers and getting help from either Mrs. Naidu (when needed) and my peers, especially when working with the CRUD data. I am the TO and was able to successfully get the CRUD and Search Bar running throughout my project. Along with the model.py works as well when you run it. I do still struggle with fully understanding the blueprint and async functions throughout the CRUD and search bar. The week before I was unable to get the search bar working, but this week I was able to figure out how to do it with the help of my peers. I was also able to get it running on my groups pages as well, as we struggled with this from before. I would like to develop my understanding of the Fetch and CRUD data as I progress throughout the project.
